---

# - hosts: kibana
#   remote_user: vagrant
#   become: yes
#   vars:
#     dockerised: true
#     kibana_elasticsearch_url: http://10.0.3.121:9200
#   roles:
#     - docker
#     - kibana

- hosts: kibana
  remote_user: vagrant
  become: yes
  vars:
    dockerised: false
    kibana_elasticsearch_url: http://10.0.3.121:9200
  roles:
    - java
    - kibana
