apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ item.name }}"
  namespace: "{{ item.namespace }}"
data:
  kibana.yml: |-
    kibana_server_host: {{ kibana_server_host }}
    kibana_server_name: {{ kibana_server_name }}
    kibana_elasticsearch_url: {{ kibana_elasticsearch_url }}
